version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=470727887694.dkr.ecr.us-east-2.amazonaws.com/chaitanya-demo
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t vamsi:latest .
      - docker tag  vamsi:latest 470727887694.dkr.ecr.us-east-2.amazonaws.com/chaitanya-demo/vamsi:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 470727887694.dkr.ecr.us-east-2.amazonaws.com/chaitanya-demo 470727887694.dkr.ecr.us-east-2.amazonaws.com/chaitanya-demo/vamsi:latest
      
